### PR TITLE
Allow collections to be never empty

### PR DESCRIPTION
**Pull request by jayvdb**
Closes https://github.com/cksac/fake-rs/issues/128

### CODE REVIEW

**Comment by cksac** [comment]
the collection now can have non-empty faker struct already, e.g. each collection type has Faker and tuple impl
```rust
impl<T, E, L> Dummy<(E, L)> for VecDeque<T>
where
    T: Dummy<E>,
    usize: Dummy<L>,
{
    fn dummy_with_rng<R: Rng + ?Sized>(config: &(E, L), rng: &mut R) -> Self {
        let len: usize = config.1.fake_with_rng(rng);
        let mut v = VecDeque::with_capacity(len);
        for _ in 0..len {
            v.push_back(config.0.fake_with_rng(rng));
        }
        v
    }
}
```

usage:
```rust
let list: VecDeque = (Faker, 1..10).fake();
```

**Comment by jayvdb** [comment]
I am aware of that, however I have a very deeply nested structure, consisting of hundreds of different structs/enums, and the top level is not a collection, so giving a range as config results in:

```rust
... =  (Faker, 1..10).fake_with_rng(&mut rng);
    |                 ^^^^^^^^^^^^^ the trait `Dummy<(Faker, std::ops::Range<{integer}>)>` is not implemented for `MyTopLevelStruct`
```

I dont want to be building specialised Fakers for all of my structure's elements, some of which are third-party data structures (e.g. geo-types).

Anyway, I'll take a look at v2.6 to see what is now possible giving your response to #128, and get back to you.

**Comment by jayvdb** [comment]
I've replied on https://github.com/cksac/fake-rs/issues/128 - I dont see how v2.6 additions solve our need.  The only way to make that work would be to have a second set of data structures littered with these `dummy` attributes, that are only used for `fake`, and then have `.into()` to convert them into our real data structures.

**Comment by cksac** [comment]
ic, how about put this behind feature gate?

**Comment by cksac** [comment]
thanks your PR too. Released 2.6.1, moved AlwaysTrueRng into fake::utils, and add extra feature for collection len

**Pull request merged**
