### PR TITLE
Semver : WIP

### PR DESCRIPTION
**Pull request by mothsART**
I think, filtering on stable/unstable version is an important feature.

I added a choice but i'm not really satisfied (breaking changed) : Ideally i wish i could do :

```
Semver(filter: crate::faker::SemverFilter);
```

and 

```
Semver();
```

I didn't find an elegant solution.

### CODE REVIEW

**Comment by mothsART** [comment]
Use semver crate should be a good idea but I don't understand how it will solve my problem.
Perhaps, you think than best implementation can look like this ?

```
Semver(EN); // return X.Y.Z or X-Y-Z-V.W (V equals "rc", "beta" or "alpha")
SemverStable(EN); // return X.Y.Z
SemverUnstable(EN); // return X-Y-Z-V.W
```

**Comment by cksac** [comment]
If Semver no need to be different in different locale, we can have different struct/enum as config to generate Sember. e.g.

```rust
pub enum SemverFaker {
     Default,
     Stable,
     Unstable,
}

impl Dummy<SemverFaker> for semver::Version {
      fn dummy_with_rng<R: Rng + ?Sized>(_: &Faker, rng: &mut R) -> Self {
             todo!()
      }
}

// later
let v = SemverFaker::Default.fake()
```
Beside SemberFaker, any struct/enum can implement Dummy for semver::Version,
more examples in [http impl](https://github.com/cksac/fake-rs/blob/master/fake/src/impls/http/mod.rs)

**Comment by mothsART** [comment]
Thanks,

What do you think about my last diff ?

Usage :

```rust
let v_one: String = Semver().fake();
```
or 
```
let v_two: String = SemverFaker::Default.fake();
```

**Comment by cksac** [comment]
Comparing for generate semver string
Option 1
```
Semver(EN); // return X.Y.Z or X-Y-Z-V.W (V equals "rc", "beta" or "alpha")
SemverStable(EN); // return X.Y.Z
SemverUnstable(EN); // return X-Y-Z-V.W
```
and
Option 2
```
Semver().fake();
SemverFaker::Default.fake();
SemverFaker::Unstable.fake();
```
I more prefer your initial suggestion (option 1). The SemverFaker maybe for generating `semver::Version` instead.

**Comment by mothsART** [comment]
i've updated with your suggestions. Sorry for waiting, i forgot it.

**Pull request merged**
