### PR TITLE
Don't require chrono's default features

### PR DESCRIPTION
**Pull request by msrd0**
This removes an unneccessary dependency on time 0.1

### CODE REVIEW

**Comment by llogiq** [comment]
chrono is by now unmaintained. At some point we may want to move to time.

**Comment by msrd0** [comment]
> chrono is by now unmaintained. At some point we may want to move to time.

I wish I could get rid of chrono, but too many dependencies are still using it, and in one way or another forcing me to use it too. At least I can try to get rid of time 0.1, which is definitely unmaintained and unneccessary at this point. I hope that at some point a newer version of time emerges as the default.

**Comment by llogiq** [comment]
I understand. Thank you anyway! We may at some point want to think about making that chrono dependency optional and allow for time as an alternative.

**Comment by msrd0** [comment]
> We may at some point want to think about making that chrono dependency optional

Which it already is? At least it's marked as such in the [`Cargo.toml`](https://github.com/cksac/fake-rs/blob/master/fake/Cargo.toml#L16) file

**Pull request merged**
