### PR TITLE
Add rust_decimal faking capabilities

### PR DESCRIPTION
**Pull request by ASAPHAANING**
Thank you for providing this excellent tool!

This PR introduces [Decimal](https://docs.rs/rust_decimal/latest/rust_decimal/) faking.
I chose not to localize it and go with an enum for configuation. I will most likely supply more configuration options in the future :)

### CODE REVIEW

**Comment by cksac** [comment]
thanks for the PR, why use enum for config instead of use each variant as config object?

**Comment by ASAPHAANING** [comment]
> thanks for the PR, why use enum for config instead of use each variant as config object?

For me to use the variants as config objects they would have to be structs, no?
I thought this was more concise but I am happy to change to what you prefer!

**Comment by cksac** [comment]
yes, please use struct for each variant. thx

**Comment by ASAPHAANING** [comment]
Already done!

**Comment by mothsART** [comment]
No tests in fake/tests/determinism.rs

**Comment by ASAPHAANING** [comment]
> No tests in fake/tests/determinism.rs ?

Ah, will add tonight. 👍

**Pull request merged**
