### PR TITLE
Implement (optional) datetime feature using chrono

### PR DESCRIPTION
**Pull request by mekagoza**
This should implement issue #11 . This is implemented using an optional Cargo feature, so it's disabled by default to minimize unnecessary dependencies and compile time. That can be changed.

@svenstaro ,  can you take a look over this and let me know if this is what you had in mind? The tests in `src/lib.rs` are instructive, and the implementation is all in `src/faker/time.rs`

### CODE REVIEW

**Comment by svenstaro** [comment]
Looks pretty good! Make sure to also update the README though.

**Comment by mekagoza** [comment]
@cksac How does everything look?

**Comment by cksac** [comment]
@mekagoza looks good. Thanks for the PR.

**Comment by mekagoza** [comment]
@cksac Not sure about this but it might be worth bumping the semver in Cargo.toml to 1.3 or whatever for this. I wanted to leave that in your hands

**Pull request merged**
