### PR TITLE
Fix country names

### PR DESCRIPTION
**Pull request by evgeniy-r**
I have fixed some typos in the `ADDRESS_COUNTRY` constant:
* `"Democratic People's Republic of Korea Republic of Korea Kuwait Kyrgyz Republic Lao People's Democratic Republic"` was in one word.
* `"'Virgin Islands, British'"` and `"'Virgin Islands, U.S.'"` had additional quotes.

### CODE REVIEW

**Comment by pickfire** [comment]
> "Democratic People's Republic of Korea Republic of Korea Kuwait Kyrgyz Republic Lao People's Democratic Republic" was in one word.

If that is the case why shouldn't `China` be `People's Republic of China`? And `Hong Kong` be `Hong Kong Special Administrative Region of the People's Republic of China`? And `Taiwan` be `Republic of China`? And `Macao` be `Macao Special Administrative Region of the People's Republic of China`?

**Comment by evgeniy-r** [comment]
I don't talk about short or long country names.
I talk about the fact that now `"Democratic People's Republic of Korea Republic of Korea Kuwait Kyrgyz Republic Lao People's Democratic Republic"` is the one item, not five.

**Comment by evgeniy-r** [comment]
And this PR adds missed quotes separating this items.

**Comment by pickfire** [comment]
Ah, I just saw it. Sorry about that, I didn't know there are multiple countries names on it.

**Pull request merged**
