### PR TITLE
Added foundation for DE_DE data

### PR DESCRIPTION
**Pull request by xoryouyou**
Hi @cksac,
I've been using your library thanks to [LukeMathWalker/zero-to-production](https://github.com/LukeMathWalker/zero-to-production/) 

Since I've had the need to generate a bit of german fake data I took a closer look into the project.

I added a `de_de.rs` module to provide a few basic attributes like State,Company Type,Names and so on from the official government ID test card data 

https://persosim.secunet.com/fileadmin/user_upload/PersoSim_Personalisierungsdaten_eID_UB.pdf

It's working with the `check_determinism` test as far as I can tell.

To verify the data that gets generated I added a `de_manual_test.rs` just so see some generic company struct on the terminal.

Run via `cargo test de_manual_test -- --nocapture` it produces some results like 
```
Company { name: "Schuster e.V.", street: "Hillebrandtgang", zipcode: "29346", city: "Musterfrau land", state: "Berlin" }
```

So far so good. :smile: 

But that is the reason I opened the PR.

`"Musterfrau land"` is not a valid city name in german.

Most city names would consist of two nouns or names and a suffix.

Germany and to further extend the "DACH" Region (Germany, Austria, Switzerland) all have a pretty different layout for thinks like street names and addresses.

And I would like to discuss how I could implement it in a way it suites the library and their users.

For example a street name might be separated by dashes if it contains one or multiple names e.g. `Karl-Marx-Allee`  https://en.wikipedia.org/wiki/Karl-Marx-Allee or can contain an apostrophe as seen here in  https://de.wikipedia.org/wiki/Stra%C3%9Fenname in `Laehr'scher Jagdweg`

There are already some  `impl` with random branching for data generation https://github.com/cksac/fake-rs/blob/32646496eba2918f133c31e594e46ee907577c50/fake/src/faker/impls/address.rs#L108

And I don't know if I should start adding `impl`s special for the `DE_DE` locale or how it would fit the overall project structure.

Any feedback or guidance is appreciated and I would gladly implement more of the german locale.

Cheers xoryouyou

### CODE REVIEW

**Comment by llogiq** [comment]
Hi there! Thank you for opening this PR! As another German (who didn't have enough time to stem this), I'm particularly happy this finally gets addressed.

With last names, I'd allow for double names by rule instead of putting them into the data. The rule should have special handling for equal last names to just return that name so we can avoid "Müller-Müller". I would avoid "Musterfrau".

Street names can be hyphenated names, last names, city names or a variety of words + any of "Straße", "Weg", "Gasse", "Allee", "Chaussee" selected with decreasing probability.

City names can be built from a variety of suffixes like. "stadt", "berg", "dorf", "kirchen", "burg", "feld", "au", "ing" or "heim" and optional prefixes "Groß ", "Klein ", "Ober", "Unter". That plus a list of name parts will give us a good selection.

**Comment by xoryouyou** [comment]
Thanks for the feedback and that is exactly why I opened the PR.

The whole cityname with prefixes, suffixes and some static strings in between opened the question in my head how to integrate it into the library.

Would you enhance the `impl` here https://github.com/cksac/fake-rs/blob/32646496eba2918f133c31e594e46ee907577c50/fake/src/faker/impls/address.rs#L35 and add all locale logic in there to branch and randomly generate a string from fiben parts or would you create a custom `impl` per locale which  could then use its custom `TPL` with `{prefix}{base}{suffix}`  ?

These are just ideas and I'm a bit lost how it could work best for the library :)

**Comment by llogiq** [comment]
Good question. Perhaps having a kind of templating functionality that we can reuse might be useful, perhaps along with a few rules (e.g. no uppercase letters after lowercase letters).

**Comment by cksac** [comment]
I would prefer templates for the default implementation, in case it does not fit for specific locale, can use impl specialisation. But not sure is it in stable or not

**Comment by xoryouyou** [comment]
Small update time.

### Data
I've added  the 50 most common firstnames for female and male
also the 100 most common lastnames.

Source:
- Firstnames
  - https://de.wiktionary.org/wiki/Verzeichnis:Deutsch/Namen/die_h%C3%A4ufigsten_m%C3%A4nnlichen_Vornamen_Deutschland
  - https://de.wiktionary.org/wiki/Verzeichnis:Deutsch/Namen/die_h%C3%A4ufigsten_weiblichen_Vornamen_Deutschlands
- Lastnames
  - https://de.wiktionary.org/wiki/Verzeichnis:Deutsch/Namen/die_h%C3%A4ufigsten_Nachnamen_Deutschlands

- GermanID Testnames:
  - https://persosim.secunet.com/fileadmin/user_upload/PersoSim_Personalisierungsdaten_nPA.pdf
  - https://persosim.secunet.com/fileadmin/user_upload/PersoSim_Personalisierungsdaten_eID_UB.pdf
  
Regarding the City names I've integrated the suggestions from @llogiq 

A sample company currently looks like this:

```
Company {
    name: "Hahn and Beck GmbH",
    address_line_1: "Weißallee 44",
    address_line_2: "Aufgang 79",
    zipcode: "38015",
    city: "Peterheim",
    state: "Nordrhein-Westfalen",
}
```

### Issues

During testing I found that only using templates will not suffice for all of the german specifics and probably for other locales too.

Some edge cases I encountered where:

#### Proper lowercasing in city names
Example: `city: "UnterHeinrich Bauerfurt"`
Should be: `city:" Unterheinrich Bauerfurt"`

Due to the `.replace` in https://github.com/cksac/fake-rs/blob/32646496eba2918f133c31e594e46ee907577c50/fake/src/faker/impls/address.rs#L43
the function simply takes a LastName and plugs it into the Template string.
which could be prevented by lowercasing all templated strings except the first one.

#### Citystates
Example: 
```
    city: "Juttafeld",
    state: "Berlin",
```
Should be:
```
    city: "Berlin",
    state: "Berlin",
```

In germany there are a few Citystates e.g. Berlin, Bremen, Hamburg. These share the same name
for City and State and therefore should not differ. 

My understanding from the examples is that the library only provides parts of bigger structures like `CompanyName()` ,`
CompanySuffix()` ,`...` and the responsibility lies with the user to generate proper aggregates like `struct GermanCompany` to handle all the specific details in their implementation using the library.

My feeling is that some kind of customization logic might be needed in the future internally in the `impls`.

#### Static content

Due to a lot of edge cases which might not be easily generated but provide a benefit for testing purposes it 
would be great to have something like `ADDRESS_CITY_NAME_STATIC` and `ADDRESS_STREET_NAME_STATIC`  which could hold names like Berlin, Frankfurt, etc.
and be randomly chosen instead of a `FirstName` or `Lastname` as it is currently done.

### Feedback 
I would really like to get your feedback on this since I have the feeling a lot of other locales will face similar problems
like ireland with the [EIRCODE ](https://www.eircode.ie/what-is-eircode) 
and a bunch of other specifications from the [INSPIRE ](https://inspire.ec.europa.eu/documents/Data_Specifications/INSPIRE_DataSpecification_AD_v3.0.pdf ) project 

Therefore we might need a bit more logic in each respective `impl<L:Data + Copy> Dummy<Type<L>>` for each locale which feels wrong due to the fact that it would force specific locale code in the core of the library.
 
Or the other way round it would make sense to have `impl`s based in each locale so `EN_IE` could implement  its own version for e.g. `PostalCode`.

And since I'm only contributing I would like to get your input on this and ask for a bit of help or examples how I could implement either way you want it to be integrated in the future :smile:

**Comment by llogiq** [comment]
Regarding the uppercase problem: I would suggest adding a function that lowercases all characters unless a) the first and b) following any whitespace. This would leave e.g. "Gross Annaheim" in uppercase but lowercase "Unterdirkfurt"

**Comment by MLNW** [comment]
Sad to see this is dead in the water. Would have been nice to fake some German data next to the other available languages.

**Comment by xoryouyou** [comment]
Yeah unfortunately my work focus changed and I didn't have any time to maintain the PR or even keep it up to date.
But if anyone is willing feel free to take it over.
I can't foresee when I'll have time to work on it again.

**Comment by xoryouyou** [comment]
Hey guys I've found a bit of spare time and merged the new master into my old branch.
Seems to work so far.

But there is still the issue regarding the casing in `city: "NeuElisabeth Zimmermannfeld"`

It feels kinda wrong to add the suggested function from @llogiq to the `impl Dummy<CityName<L>> for String` at https://github.com/cksac/fake-rs/blob/8c92743c979e899ac5f921788b198b04e6c35bfc/fake/src/faker/impls/address.rs#L35

Is there a way in which I could add a specific `impl` for only the `DE_DE` locale ?

This would open up the opportunity to provide locale specific logic and solve issues like my uppercase concatenation one.

Cheers and Happy Holidays 🎄

**Comment by cksac** [comment]
This library main goal is not to generate real data, it generates data comply to the data format of given type. 
For uses case need more realistic data can define a new Config type, i.e “RealistCityName” and implement dummy for it.

Therefore, I think current PR is sufficient?

**Comment by cksac** [comment]
I added `ADDRESS_CITY_GEN_FN` in Data trait and update the implementation of `impl<L: Data + Copy> Dummy<CityName<L>> for String` in latest master

you can now implement custom logic for it like below
```rust 
impl Data for MyLocale {
    const ADDRESS_CITY_GEN_FN: Option<fn() -> String> = Some(my_city_fn);
}

fn my_city_fn() -> String {
    "custom logic".to_owned()
}
```

**Comment by xoryouyou** [comment]
Hey @cksac  I've added a first little `ADDRESS_CITY_GEN_FN`

It tries to mimic the existing code structure from `address.rs` but adds some more common cases for the german locale e.g. adding a dash in concatenated names or suffixing a rivers name to a city.

One problem I faced was that I could not access the `thread_rng` from `main.rs` since function pointers don't support generic parameters.

So I could not change 

```rust
fn() -> String
```

to

```rust

fn <R: Rng + ?Sized>(rng: &mut R)
```
which is unfortunate and I haven't measured the performance impact of generating a new `rand::thread_rng`  on the fly.



Here is some generated sampledata which looks good to me and should cover most edge cases ( dashes spaces and parantheses in city names)

```
"Hans Beckerfurt"
"Neu-Gerda Schubertheim"
"Ober Thomasing"
"Alt-Beate Möllerstadt (Mosel)"
"Jutta Maierstadt"
"Oberschröderkirchen"
"Altgüntherstadt"
"Unter-Ursula Rothfurt"
"Altbrandtfurt"
```

**Comment by cksac** [comment]
yes, that's need to be addressed later. 
I will update later the gen fn  later when I figure out a way. 
This PR LGTM, thanks

**Comment by xoryouyou** [comment]
Perfect! I made a last small commit removing my manual test file and adding the `de_de` locale to the table in the readme.
@MLNW  looks like we finally get `de_de` after all those years, sorry for taking so long 😅

**Comment by MLNW** [comment]
Nice, thank you!

**Pull request merged**
